name: Nintendo Museum Calendar Check

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Check 2025-06-28
        run: |
          echo "开始执行6/28任务..."
          curl -H "Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}" "https://fetch-nintendo-calendar.vercel.app/api/cron?targetDate=2025-06-28"
          echo "定时任务执行完成"
      
      - name: Check 2025-06-29
        run: |
          echo "开始执行6/29任务..."
          curl -H "Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}" "https://fetch-nintendo-calendar.vercel.app/api/cron?targetDate=2025-06-29"
          echo "定时任务执行完成"
      
      - name: Check 2025-06-30
        run: |
          echo "开始执行6/30任务..."
          curl -H "Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}" "https://fetch-nintendo-calendar.vercel.app/api/cron?targetDate=2025-06-30"
          echo "定时任务执行完成" 