name: Nintendo Museum Calendar Check

on:
  schedule:
    - cron: '*/59 * * * *'  # 每30分钟执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  regular-check:
    if: github.event.schedule == '*/30 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Check 2025-06-29
        run: |
          echo "开始执行6/29任务..."
          curl "https://fetch-nintendo-calendar.vercel.app/api/calendar?date=2025-06-29"
          echo "定时任务执行完成"
