name: Nintendo Museum Calendar Check

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          echo "开始执行定时任务..."
          curl -H "Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}" https://fetch-nintendo-calendar.vercel.app/api/cron
          echo "定时任务执行完成" 