name: Nintendo Museum Calendar Check

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点执行
  workflow_dispatch:  # 允许手动触发

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          echo "开始执行定时任务..."
          curl -H "Authorization: Bearer ${{ secrets.CRON_SECRET_KEY }}" https://你的域名/api/cron
          echo "定时任务执行完成" 